import os
import sys

def main():
    print("--- Generating setup_lang.bat ---")

    # 1. Detect the correct path to PyBabel on your system
    python_dir = os.path.dirname(sys.executable)
    # Windows path to Scripts folder
    pybabel_path = os.path.join(python_dir, "Scripts", "pybabel.exe")

    # Verify if it exists, otherwise fallback to global command
    if not os.path.exists(pybabel_path):
        print("Could not find specific pybabel.exe, using default command.")
        pybabel_path = "pybabel"
    else:
        print(f"Found PyBabel at: {pybabel_path}")

    # 2. Define the Batch File Content (No Emojis to prevent errors)
    bat_content = f"""@echo off
:: This file was generated by translation.py
:: It contains the fixed configuration and specific paths for your machine

set PYBABEL="{pybabel_path}"

echo ===================================================
echo      PTAH STUDIOS TRANSLATION SETUP
echo ===================================================

echo.
echo --- 1. Creating babel.cfg (Fixing Jinja2 error) ---
(
echo [python: **.py]
echo [jinja2: **/templates/**.html]
) > babel.cfg

echo.
echo --- 2. Extracting texts to messages.pot ---
%PYBABEL% extract -F babel.cfg -o messages.pot .

IF %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Extraction failed.
    pause
    exit /b
)

echo.
echo --- 3. Setting up Arabic Folder ---
if not exist "translations\\ar" (
    echo [NEW] Creating Arabic translation folder...
    %PYBABEL% init -i messages.pot -d translations -l ar
) else (
    echo [UPDATE] Updating existing Arabic folder...
    %PYBABEL% update -i messages.pot -d translations
)

echo.
echo ===================================================
echo [SUCCESS] Files are ready.
echo ===================================================
echo.
echo NEXT STEPS:
echo 1. Go to: translations/ar/LC_MESSAGES/messages.po
echo 2. Open it and translate the msgstr "" lines.
echo 3. To apply changes, run this command:
echo    %PYBABEL% compile -d translations
echo.
pause
"""

    # 3. Write the file to disk (Force UTF-8 just in case, but content is now safe ASCII)
    try:
        with open("setup_lang.bat", "w", encoding="utf-8") as f:
            f.write(bat_content)
        print("Success: 'setup_lang.bat' has been created.")
        print("Action: Go to your folder and double-click 'setup_lang.bat' now.")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    main()